version: 2

builds:
  - id: tsgo-wasm
    dir: tsgo
    main: ./cmd/tsgo
    binary: tsgo
    goos: [js]
    goarch: [wasm]
    env:
      - CGO_ENABLED=0

archives:
  - formats: tar.gz
    name_template: '{{ .Binary }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - src: tsgo/built/local/*
        strip_parent: true

changelog:
  disable: true

release:
  header: |
    Daily automated WASM build of TypeScript Go from [`microsoft/typescript-go@{{ .Env.TSGO_COMMIT_SHORT }}`](https://github.com/microsoft/typescript-go/commit/{{ .Env.TSGO_COMMIT }}).

    Build date: {{ .Tag }}
